package pdf.formatter.pdf_formatter.exceptionHandling;

public class DocumentNotFoundException extends RuntimeException {

  /**
   * Autogenerated by IDE, why?
   */
  private static final long serialVersionUID = 1L;

  public DocumentNotFoundException(Long id) {
    super("Could not find document " + id);
  }
}
